### ISSUE TITLE
Some Items Missing from Search

### ISSUE THREAD

**Issue by adane** [Tizra/Tizra-Customer-Tracker#422] opened 2016-10-24 02:57 UTC
At least one of the items that used to appear in this search...

http://einsteinpapers.press.princeton.edu/~searchResults?searchMode=quick&searchText=wasserwellen&context=-2&sortField=Sort

...is no longer appearing.

**Comment by daviddurand** [comment] 2016-10-25 15:23
Since I'm not sure what item was missing, I can't tell if this is still an issue. However, I believe that any remaining German search problems should be fixed at this point.

**Comment by daviddurand** [comment] 2016-10-25 15:25
Accpding to this old email, the problem is fixed:

Here’s the search I do in demos…

http://einsteinpapers.press.princeton.edu/~searchResults?searchMode=quick&searchText=wasserwellen&context=-2&sortField=Sort

And here’s the page that used to come up (among the first couple of hits) that doesn’t anymore…

http://einsteinpapers.press.princeton.edu/vol6-doc/428?highlightText=wasserwellen

**Closed as completed by daviddurand** 2016-10-25 15:25 UTC
Labels: bug
