### ISSUE TITLE
Character entity problems

### ISSUE THREAD

**Issue by orangedrink** [Tizra/Tizra-Customer-Tracker#161] opened 2012-12-13 17:02 UTC
Has something changed with this recently? I think we're seeing our entities double encoded. See the capture below from TRB to see what I mean.

http://screencast.com/t/wIi8rZURvAS

We have a lot of sites set up this way so I'm hoping this can be fixed. Let me know if you have any questions.

Thanks!

**Comment by daviddurand** [comment] 2012-12-13 20:03
There's no direct change that I can find -- though I can't check all of the thousands of changes. The significant change to the most likely spot for a problem was made in july of 2011.  What may have changed is the behavior of the bulk import. The problem is that semicolons separate items in lists, so that given a string like: `De Palma, Andr&#233;;Perali, Federico;Picard, Nathalie;Scorbureanu, Alexandrina Ioana`  it's impossible to know if there's an entity or an empty list. The keyword picker has some complex stuff to allow `;` in values, but that only works because the keyword picker works on the string after it's broken up, and so the quoting of semicolon can be done (and undone) in the right spots.

We could substitute all occurrences of `&#digits;` on any input, but then there are other problems.

It's worth noting that just using `é` works perfectly well, as we do all unicode. Indeed this is one of my test strings: `amazon اشdfdعار ژاک پرور` really much harder.

I think I can add a supertagger feature to normalize entities, and I can change the bulk-loader to do so as well.

It's hard to be sure what's the right solution...

**Comment by orangedrink** [comment] 2012-12-13 21:42
I think as long as we can put a character entity in and have it come out the same way (and be rendered as the correct character by the browser of course) we will be ok. 

It looks like this is working fine on other sites so feel free to close this issue. If I find out anything relevant about this  case I'll let you know. Feel free to close this issue.

Thanks!

**Comment by orangedrink** [comment] 2012-12-13 22:03
Ugh.. I'm sorry. I didn't understand the part about empty lists at first. Is there a way we can escape the necessary semicolons? For example by using "\;" or some other encoding?  If unicode is the only option we can work with that. Thank you.

**Comment by daviddurand** [comment] 2012-12-13 22:08
Be aware that this problem will exist for any field that is a "list" field except for keyword lists (which have a special editor). In particular, the system Authors is a list field, and that's the right type to use for other lists of items that may each contain searchable words.

Your question about escaping is to the point, and there is an escape code, but it will only work if the list is processed -- something that you can't specify in the system right now.

I'll post to this issue once I can decide how to make an improvement without introducing compatibility problems. For text, string, HTML, keyword, etc. it's not a problem, but it is a problem with List.

**Comment by daviddurand** [comment] 2012-12-13 23:40
I'm putting in a fix tonight. The escape for semi-colon is `%3B`. Just a special case of URL escaping.

**Comment by daviddurand** [comment] 2012-12-14 16:37
I had to back out of my idea for a quick fix on this, as I remembered the problem  -- many sites, including some of yours, have & characters in them that are not entity references, and this can confuse the markup situation if the strings are not escaped -- plus we have had other problems with characters that are significant in HTML/XML.

I've reopened this issue, and relabeled it "enhancement". The first step is:
- a supertagger option to convert character entities in a field. This will let you update existing fields that may have character entities so that they are stored in unicode directly, which works fine.

The second step will take a little longer, but is more on the lines of the fix we were both originally thinking of:
- some way to explicitly label data types as allowing HTML inside them; I'm not yet sure how that will be indicated, but the way it will work is clear. When selected this option will disable all the HTML escaping that we do on fields -- Imposing the obligation on the publisher to make sure that the contents of the field do not cause tag parsing errors when displayed.

**Comment by daviddurand** [comment] 2012-12-16 00:28
I revisited this after a little more thought and code review. It turns out that things were not previously consistent -- properties were escaped in some places, and unescaped in others -- List-valued items were one of the places where escaping was not done. I don't know why entities worked before. They could have broken when we implemented markup around list items in author indexes, or you may have been using plain string fields on some sites, 

Now, the semicolons would have caused troubles in list values, but I suspect that on many sites you just used a string value for your Authors "display" fields, rather than the list value that is used in the system field, and so the entities would work.

While the internal escaping is based on `%3B` it's really hard to read and to remember, so I took your suggestion about using backslash escapes.

So what has been done now is this:
- Markup in any property will be displayed into the page without HTML escaping.
- For list values only:
  -  In a list value, you can escape a semicolon by using `\;`. 
  - If you need to use a `\` you should use `\\`.
  - Currently, single `\` will show up as `\`. But you should not count on that, as someday `\` followed by other characters may become significant for the system. 
- For all other property types like html, string, etc, there is no special behavior for `\` or `;`.
- For special characters, it's easier to just paste them into the browser and have them in unicode.

Someday we may add supertagger features like I was talking about, but this seems to be good enough for now.

**Closed as completed by daviddurand** 2012-12-16 00:28 UTC
Labels: enhancement, client-support
