### ISSUE TITLE
"Remember Login" -- Does not work on some Webkit-based browsers

### ISSUE THREAD

**Issue by ghost** [Tizra/Tizra-Customer-Tracker#51] opened 2012-04-18 15:13 UTC
When I use remember login, nothing is remembered when I return to the site after logging out.

What should be happening, and is there anything that we have done to disrupt it or is this a system bug?

Thanks.

**Comment by daviddurand** [comment] 2012-04-20 15:20
There are some known problems with certain browsers (mostly Webkit-based on Mac OS X). Basically cookies are ignored on redirects due to a browser bug in Safari and Chrome. Workarounds are pretty tough, and so far you are the first person other than me and Abe to complain about it, (I assume that at least a few other people must have noticed) so it has not seemed a burning issue.

For administrative users there is a workaround if you want to save your credentials:
1. go to /admin/main
2. send a blank username and password (that will give you the login page again, but the host will be secure.agilepdf.com) 
3. log in with the remember box checked.

Once you've done this, the cookie will be properly accepted. I know it's baroque. However, due to the same bug, once you've dont this I believe you'll only be able to remove the cookie by logging out from the administrative tool, or removing it manually.

**Comment by ghost** [comment] 2012-04-20 15:27
A large amount of people are complaining about this with ASPPA.

And, this isn't just happening with Webkit based browsers on a mac. It doesn't seem to work on any browser for any user.

Please let me know when you plan to fix this so I can un-hide it from all of our sites. 

Thanks.

**Comment by daviddurand** [comment] 2012-04-20 17:44
Can you give me some more information on with which browsers (and versions) customers are seeing the issue?

I am not having problems on Firefox 10.0.2 (and I never did in past versions either).

I'll check IE again, but since Firefox is working, I'm not expecting a change there.

Here's the stackoverflow page that describes the problem as I understand it:

http://stackoverflow.com/questions/1144894/safari-doesnt-set-cookie-but-ie-ff-does

**Comment by daviddurand** [comment] 2012-04-20 19:24
I looked through the whole flow again and found a few places where cookies were getting set in the application, but were not getting transmitted to the client. I also added explicit domain annotations to the cookies, and that seems to have made a difference with the browser bug -- So I'm now hopeful that the feature will be really working for all the browsers.

**Comment by ghost** [comment] 2012-04-20 19:40
At elibrary.asppa.org.
IE9 Doesn't work
Chrome Doesn't work
 -- A drop down of previous usernames shows up, but I think that is a browser feature
Firefox Doesn't work
 -- A drop down of previous usernames shows up, but I think that is a browser feature

http://omniplayground.tizrapublisher.com/
IE9 Doesn't work
Chrome Doesn't work
 -- A drop down of previous usernames shows up, but I think that is a browser feature
Firefox Doesn't work
 -- A drop down of previous usernames shows up, but I think that is a browser feature

Should I be testing on a specific page or site?

**Comment by daviddurand** [comment] 2012-04-20 21:20
OK, maybe we also have a question about how it was supposed to work.
Since I never had a problem with any version of firefox, I suspect that your check is not testing what you think it is -- the actual behavior is more subtle than you might expect. I don't know what versions of Firefox or Chrome you are testing with, but I'm quite sure that Firefox has always worked..
So here's how to test it:
Logging in with the checkbox selected will mean that at later times you will be automatically logged in -- but only at the exact point that you attempt to access restricted content. Basically we only check for a saved login when we need to -- when we are about to display an access denied on some content.
So if you are not checking what happens when accessing content that requires a logged-in user with a license, you may not actually be testing the feature at all.You can't look at what happens to the login box on the home page to see if it logged the user in.  Also, if you log out, any saved logins that you may have made will be eliminated. 
So to test the system to see if the cookie was set, you either have to quit the browser completely, or you have to manually delete the JSESSION cookie, and then attempt to access some restricted pages. The delayed check for logins is important for search engines and avoids redirecting people through the access control server when it's not necessary.

**Comment by daviddurand** [comment] 2012-04-20 21:22
In any case, I responded to your mail so you can do some tests, but I came back to this because I am about to close the ticket because I think I've actually fixed the problem, fixes that you should be able to see tomorrow. If either of us finds the that problem persists tomorrow with the correct test, then I'll reopen the ticket.

**Comment by ghost** [comment] 2012-04-20 21:33
I'll test it, but now that you have explained "What should be happening" I will check that.

I think the issue with all the asppa users is that they, and myself include, expect it to remember the username so they don't need to enter it when they return. If i test it out with the information you provided earlier (sorry haven't read it completely yet, need to meet family for dinner) and everything works as you explain it, then I will let people know what it actually is suppose to do. 

Thank you.

**Comment by daviddurand** [comment] 2012-04-20 21:41
That's fine -- in any case, you might as well test tomorrow morning because I'll have to restart the server before there is a hope for Chrome and Safari to work.

**Comment by daviddurand** [comment] 2012-04-21 21:10
They won't have to re-enter the user name when they come back, but
they will just need to ignore the login box -- that said, I have an
idea about how I can make things a little more self-evident.

---

David G. Durand
CEO / CTO
Tizra
9 Catalpa Road
Providence, RI 02906

Email: david.durand@tizra.com
Phone: +1 401 935-5317
FAX: +1 401 273-5171
Web: http://www.tizra.com/
Blog: http://blog.tizra.com/

Online publishing unbound.

On Fri, Apr 20, 2012 at 5:33 PM, Ryan Hood
reply@reply.github.com
wrote:

**Comment by daviddurand** [comment] 2012-04-22 17:09
I am pushing a change to make the persistent login immediately visible, rather than just on access denied.

This does not change the way that access control works (now that the bugs are gone), but it lets the user understand that it is working for them.

**Comment by ghost** [comment] 2012-04-23 15:49
Now I can't seem to log out of the ASPPA site unless I delete the cookies.

**Comment by daviddurand** [comment] 2012-04-23 17:49
What browser versions? I was just checking on the ASPPA site with no trouble in Chrome, Firefox, Safari...

I'll double check Explorer, but unusually I hadn't had any trouble with it and this cookie stuff...

**Comment by ghost** [comment] 2012-04-23 18:07
I can't log out of Chrome or Firefox. Haven't tested on any other browsers yet.

See this video for what I'm experiencing for Chrome. Firefox is the same thing, but only wanted to send one video.
http://screencast.com/t/ZcaTmm0E9Oab

**Comment by daviddurand** [comment] 2012-04-23 18:17
Well, it looks just like what I'm seeing, except that I log out.
In chrome, can you inspect the page, and look at the cookies in the resources tab? (You can also do it in preferences).
I'd like to see them before you log in, after, and and after a logout attempt.

The other thing would be to track the redirections with the network tab on the inspector -- if you want to go across redirects you have to select the red "recording" button on the network tool.

Are you using any kind of proxy server that might be caching the cookies?

**Comment by daviddurand** [comment] 2012-04-23 18:24
I just had a thought. You might have a login cookie on your account at secure.agilepdf.com from before the time that I fixed the redirect bug (the only way to do that in chrome before the fix was via an administrative login, so it would not affect an end-user) -- The current logout function might not be deleting the old cookie. (the original cookie did not have a domain set, explicitly, while the new ones do). The old cookie would still be able to log you in though.

I think that makes a lot of sense: check cookies for the secure.agilepdf.com domain, and make sure they are all deleted, and then restart the process again. Or test with a new, end-user account -- always a good idea anyway, as there are sometimes differences, as I suspect here.

**Comment by ghost** [comment] 2012-04-23 18:51
Clearing the cookies from secure.agile seemed to fix that issue.

**Comment by orangedrink** [comment] 2012-07-05 14:35
I'm getting questions about this from SDE. The intended behavior of the remember password checkbox doesn't make much sense on this site since the user needs to log in before they are able to get to the content they need.

Any thoughts on this? Any better solution for them than hiding the checkbox?

My thoughts are that even on a site where this does make sense it's too confusing to be useful.

Thanks

**Comment by daviddurand** [comment] 2012-07-05 16:35
I think you'll have to explain the current problem fully. By the end of this ticket, I'd made a number of significant changes to the password function, and the whole login process, just to ensure that things would be clearer for users.

In particular:
- I fixed the Safari/Chrome bug where the "keep me logged in" didn't always work and where users on those browsers could not log out.
- I fixed the page delivery process so that if a user had selected the "keep me logged in" option, they would be logged in immediately on access, not just on the first access-controlled page.
- I fixed the IP address login to take effect immediately on accessing the site. (the drawback to this is now it's _not_ possible to log out from an IP address login -- though logging into additional accounts is possible if the site chooses to enable it).

Given the first couple of adjustments, I think that the feature may make sense for SDE.What's your take on it? Or is there something not working this way?

**Comment by orangedrink** [comment] 2012-07-05 16:48
No it's working the way you describe and that seems to be a good way for this to work. Just not exactly what people are expecting I guess.

I'll explain this to Melissa at SDE and let you know if she has any questions.

Thanks!

**Comment by orangedrink** [comment] 2012-07-05 16:51
How long does the site remember a user before they will need to log in again?

**Comment by daviddurand** [comment] 2012-07-05 17:00
A year.

The original features I described had some definite drawbacks, due to implementation compromises I've finally been able to eliminate .I think what we've currently got is certainly what I'd expect from many other sites on the web -- but if there is something confusing there, we'd like to know so we can fix it.

Or are they worrying about the specific process that people will go through if we have to reset their passwords, so that they'll have to run through a variant of the login process to set their new password? That recovery process is really a variant way into the "account claiming" process, and not related to the normal "forgot password" path....

**Comment by orangedrink** [comment] 2012-07-05 19:22
I think people are expecting the username and password fields to automatically populate like it would on most other sites that have a similar checkbox. IMO the way it is now it does the same job and saves a click on the login button.

I can only guess at what the users are describing since I got this information 2rd hand. Thanks for your help!

**Comment by ghost** [comment] 2012-07-23 18:01
David, 
I don't think the problem is with the functionality, but with the language. On most sites when you click on "remember me", it preloads this information into the fields but doesn't keep you logged in. 
Sites that keep you logged in specifically say "Stay Logged In". 

For example, Facebook.com says "Keep me logged in" under the sign in and google say "Stay signed in". 
This is clearer to the end user what is going to happen when you check the box. 

If "Remember login" can't be changed so that it remembers the login info but doesn't keep people logged in, we think that it would be better to change the text to "Stay signed in" or "Keep me logged in" to better match the function. 
- or - 
  If at all possible, allow us to edit the text that goes along with that button.

We need to get this resolved because it is causing issues with ASPPA's site because of their concurrent user limitations. 

Thanks,
Ryan

**Comment by daviddurand** [comment] 2012-07-23 18:22
OK, this is making sense now.

I'll see what I can do about adding options to change the language.

But we should think carefully about what is happening, because the cookie does not affect concurrencies or any of that stuff, so there may be something else going on. Automatic logins should time out in 30 minutes anyway -- The time that the cookie will automatically log them in for is no longer than the normal session time.

Since users are not really aware of session lengths (except for concurrency), this may not make a difference. It's worth thinking about though, to make sure that we don't keep the confusion going with a new "keep me logged in" language that doesn't make clear that the breakage is only 30 minutes or so.

What our cookie really does is:
- log someone in automatically on their next visit.
- keep doing so a year
- unless they log out explicitly, which removes the auto login.
- with 30 minute session timeouts in any case.

All based on the assumption that you did not change session length on SDE as you did for ASPPA.

If the logins are all individual, there really shouldn't be be significant concurrency issues. What seems to be happening, exactly, around concurrency?

**Comment by ghost** [comment] 2012-07-23 18:31
Actually, if I think about this, with ASPPA the issue is that people are confused by the functionality of the button especially with the time out. The concurrency is an issue of not realizing that not logging out can cause issues for other users. Our best bet for ASPPA would probably be to hide it completely.

For SDE, I know it is a confusion of functionality and I think a change in language would just make this a little more clear. 

Plus, we should probably put some information in our help section that explains how everything works.
Let me know if I'm understanding this correctly:
If I log in and check the box, I will automatically be logged in my next visit. But, if I allow the session to timeout, I will have to log in again. But, If I come back another time, I will be automatically logged in even though my session had timed out on a previous occasion.
If I choose to logout, I will not be automatically logged in the next time, no matter if I checked the box my previous time I logged in.

I may have just restated what you said above, but I want to make sure I'm completely getting this so that we can instruct our customers better and provide better user support when possible.

Thank you!

**Comment by daviddurand** [comment] 2012-07-23 18:57
On ASPPA: they wanted the current behavior, even though I warned them about the user support implications, because they want incentives for customers to buy extra licenses. This probably means that your life will always be a little difficult with this customer unless they change their minds.

Your summary is not quite right. Here it is point by point:

> If I log in and check the box, I will automatically be logged in my next visit.
- yes
  
  > But, if I allow the session to timeout, I will have to log in again. 
- Not exactly. When a session times out it is gone. On your next access to the site, you should be automatically logged in again with a freshly created session (even if you didn't close the browser). There are rare cases when you might get a cookie error, for instance  if you retry an access denied page after the original session has expired.
  
  > But, If I come back another time, I will be automatically logged in even though my session had timed out on a previous occasion.
- Yes
  
  > If I choose to logout, I will not be automatically logged in the next time, no matter if I checked the box my previous time I logged in.
- Yes.

The key here is that the server can't actually tell the difference between a fresh browser and an expired session -- they look the same at the server end.

**Comment by ghost** [comment] 2012-07-23 18:59
Perfect. Thanks.

Let us know if you make any progress on the language of the button.

**Comment by daviddurand** [comment] 2013-05-15 22:00
closing old bugs

**Closed as completed by daviddurand** 2013-05-15 22:00 UTC
Labels: bug, enhancement, client-support
