### ISSUE TITLE
Chapter 1A not showing PDF files on elibrary.asppa.org.

### ISSUE THREAD

**Issue by orangedrink** [Tizra/Tizra-Customer-Tracker#183] opened 2013-03-04 16:11 UTC
To reproduce visit this link: http://elibrary.asppa.org/erisa-outline-book-chapter-1a/1

Let me know if you have any questions.

**Comment by orangedrink** [comment] 2013-03-04 16:14
Ryan was able to get this fixed but still probably a good idea for you to be aware of the problem.

**Comment by daviddurand** [comment] 2013-03-04 16:50
Nope, there's still a problem there...

If you want the 2013 version, you should unpublish and republish the document, which ought to fix things. If you need to have 2012 up for the live pages while staging 2013, I'd put 2012 in place, republish it, and do the 2013 work on a separate document while I look into this and the ToC problem, which may be related.

**Comment by orangedrink** [comment] 2013-03-04 16:56
That's not an option since our cross links aren't going to work if we do 2013 in a separate document. Please hurry. This is a very sensitive customer.

**Comment by daviddurand** [comment] 2013-03-04 21:32
The cause of this problem is the same as #184, so closing as a duplicate.

**Closed as completed by daviddurand** 2013-03-04 21:32 UTC
Labels: bug, duplicate
