### ISSUE TITLE
Error on Adding License to Account Set

### ISSUE THREAD

**Issue by adane** [Tizra/Tizra-Customer-Tracker#334] opened 2014-04-07 13:51 UTC
To reproduce the error, create an Account Set, then click the "Create New..." button to create a license.  The attached error message is displayed.
![2014-04-07 09 49 13 am](https://cloud.githubusercontent.com/assets/1355614/2631664/c37424ae-be5b-11e3-8e0a-407e35643d31.png)

**Comment by daviddurand** [comment] 2014-04-10 17:05
This does not happen for all sites.

I found that this problem is caused by excerpts with bad page ranges in them. An overzealous error check interrupts processing that depends refers to the pages in these excerpts. this includes calculating their names for display of offers. A fix for this issue will be in place tonight. If you need a workaround, and can figure out know what excerpt(s) are creating problems, you can delete them.

**Closed as completed** 2014-04-10 17:23 UTC
Labels: bug
