### ISSUE TITLE
Macro for to display message when concurrency limit is exceeded

### ISSUE THREAD

**Issue by adane** [Tizra/Tizra-Customer-Tracker#38] opened 2012-03-12 20:02 UTC
From Ryan Hood: 

I just discussed the concurrent license paywall with ASPPA and they feel that it would be better to have a specific paywall message for concurrent users.
The goal would be to help drive traffic, and a clear explanation of what is happening would be help that.

If you and Dave can work out a macro "that ONLY appears when the reason access is denied is that the concurrent session limit has been exceeded" that would be great.
Please let us know the costs and timing of this so I can share with ASPPA's account manager. I have also included Steve and Sean to help coordinate priorities.

**Comment by daviddurand** [comment] 2012-04-13 16:12
Duplicate of #38

**Closed as completed by daviddurand** 2012-04-13 16:12 UTC
Labels: enhancement, duplicate
