### ISSUE TITLE
Excerpt deletion error

### ISSUE THREAD

**Issue by GWPublisher** [Tizra/Tizra-Customer-Tracker#446] opened 2018-01-26 14:38 UTC
We are seeing an error after deleting an excerpt. The excerpt is deleting, but it is giving an error after deleting, and showing the entire list of excerpts inside of the document excerpt list. Attached is a screenshot.
![excerpt_error_message](https://user-images.githubusercontent.com/4049888/35444475-48110ae6-0274-11e8-9b46-948b914b8939.jpg)

**Comment by daviddurand** [comment] 2018-01-26 15:07
This error should be fixed when we next update your server. (It's been fixed on the shared platform). We are hoping to do that this weekend due to some other problems that are happening (the bad slowdowns).

**Closed as completed** 2018-07-16 23:53 UTC
Labels: bug, has-workaround

**Comment by daviddurand** [comment] 2018-07-18 23:25
Duplicate of #430
