### ISSUE TITLE
Still prefer %HOME_PATH% macro to function in the global header

### ISSUE THREAD

**Issue by orangedrink** [Tizra/Tizra-Customer-Tracker#67] opened 2012-06-15 20:38 UTC
When we were talking about this previously I didn't realize that we are counting on the CSS in the tizra system to override any external CSS file we've linked. Putting calls to our external CSS inside free HTML blocks inside the layout editor will cause our external CSS files to override the CSS found in the back end correct? 

Is there another alternative to making this work inside the global header where the CSS in presentation>stylesheet will override our external CSS files?

**Comment by daviddurand** [comment] 2012-06-18 16:23
The relative importance of CSS is the same on the live and export sites. CSS is last-loaded wins, so inline styles in HTML blocks will generally win. External CSS links will obviously cause other problems since people may not be online when using a CD-ROM. Using CSS's include features would let you get away from HTML-based inclusions, and perhaps you can use media variations to ignore the external stylesheets. At least it would make tracking down all the styles used on a site much easier.

 One of the reasons that I'd like to get all CSS into the same system is that we can then look at managing it more intelligently. If you want to to have variations in the markup between the exported and online versions of a site, you will have to vary the designs. Sorry, but I can't really tell what's going on in an HTML block.

Flattening all the CSS into one file before delivery (and putting it into the Tizra CSS form), will have a very positive effect on site performance, as well as possibly making it easier to override things on export -- but you would need a way to manage that at your end, given that your stylesheets are currently broken into various bits and pieces.

You might get some management mileage out of creating stylesheets using full-text presentation properties, but unfortunately, large inline stylesheets will make things very big and slow.

**Comment by orangedrink** [comment] 2012-06-18 20:18
Hmm.. I think we're both a little off base here. This is from the SOW:

"Omnipress will be able to add scripts and stylesheets specific to the static version of
the site via an interface similar to the one now provided for editing the global site
header."

The important ways that we need this to be similar are for it to fall in the same place in the code as the web version of the global header and for it to be copied over with our design templates

**Comment by daviddurand** [comment] 2012-06-18 21:15
Yep, and the way that was delivered is by making it possible to use any design for the static export, so you can just change the global CSS (or the global site header) as an alternate design for export-use. So it's actually an interface that's identical to the way it's handled on the web.

The place where I blew it was the Title/Author Indexes, which I still have to do. I misremembered that they were out of scope, during the implementation and no-one noticed in any of the initial testing.

**Comment by orangedrink** [comment] 2012-06-19 21:56
Identical except that the file structure prevents our links inside that global header from working on all pages of the export since the home page is not in a sub folder like all the other site pages are.

**Comment by daviddurand** [comment] 2012-06-20 15:25
Can you give me some examples of specific links you want to support? are they relative or absolute?
I'm trying to think of a way that makes sense for the long run, and not just a patch.

I'm just realizing that I've lost a lot of context.
I also see that the old item is not in the tracker, but was in a long, and relatively confusing email thread. I'm not sure that I can summarize that well in this place, but here are a few things that I can pick out:
- Macros don't work in the HTML header.
- I'm reluctant to make them do so because of potential performance issues, and even more so because the way you are managing site content currently has some real support issues. Those problems are not silly, but result at least in part from the fact that you are working around things that were designed for typical Tizra customers, who do not have a large number of identical sites that need to share some (but not all) design information.
- %HOME_PATH% was created, but is not substituted in the HTML header.
- You don't want to put stylesheet content into the Tizra global stylesheet, or into the HTML for management reasons.
- URL oddities affecting caching were fixed.
- relative URLs are desired, but I'm not sure where CSS is actually stored -- in Design parameters?

**Comment by orangedrink** [comment] 2012-06-20 17:02
OK. One example would be linking to our css. On the web it looks like this:
&lt;link type="text/css" href="//s3.amazonaws.com/kc-assets/2-lib/css/base.css" rel="Stylesheet" media="screen" />

On the export it would need to look something like this:
&lt;link type="text/css" href="../css/base.css" rel="Stylesheet" media="screen" />

Except on the home page where it would have to look like 
<link type="text/css" href="css/base.css" rel="Stylesheet" media="screen" />

Does that help?

**Comment by orangedrink** [comment] 2012-06-25 21:12
Using CSS imports seems to be working. I'll let you know if I have any questions.

**Comment by ghost** [comment] 2012-06-26 13:44
@import doesn't work correctly with IE 8 and below when setting up screen and print styles. Unless tizra stops forcing all versions of IE to act like IE 7 we shouldn't use this for importing css. 

Our default css will have to remain in the global header.

**Comment by orangedrink** [comment] 2012-07-03 15:07
Any thoughts or updates on this?

**Comment by daviddurand** [comment] 2012-07-05 17:35
Sounds like eliminating the fallback header for IE would solve the remaining problems? (As well as making you happier in any case...)

If that's true, I think it tilts the balance on that long-lived issue. I'll come up with a way to make that header optional, as we should not hold back site designs to what old versions of IE support. It was there to allow some older sites and designs to work properly, and I'll try to get it in place in some other way.

**Comment by orangedrink** [comment] 2012-07-06 18:54
I'm definitely in favor of that.

**Comment by orangedrink** [comment] 2012-07-18 16:25
Any progress?

**Comment by orangedrink** [comment] 2012-07-23 14:52
I'm not sure why you are referencing issue 52 here. Have you been able to implement this yet?

**Comment by orangedrink** [comment] 2012-08-03 18:25
The first three lines of my css look like this inside Tizra:
     @import url('%HOME_PATH%/css/screen.css');
     @import url('%HOME_PATH%/css/base.css');
     @import url('%HOME_PATH%/css/print.css');

But the CSS comes out with an error:
     Unknown template call BAD@import url('/css/screen.css');
     @import url('/css/base.css');
     @import url('/css/print.css');

I'm supposed to be using %HOME_PATH% here right?

**Comment by orangedrink** [comment] 2012-08-06 13:13
Have you had a chance to look at this?

**Comment by SeanLawler** [comment] 2012-08-07 15:34
Hey guys, any word?  We'd love to put static output to bed as soon as possible so we can move on to new development.  Thanks.

**Comment by daviddurand** [comment] 2012-08-07 17:56
Sorry, wasn't aware that this is related to the site export. Also, I wasn't seeing anything that needed to change in the system.

I think your problem is just basic HTML relative paths. The extra slash in URLs like the following is causing the problem:

`%HOME_PATH%/css/screen.css`

If you use the browser inspector on the web site, you can see that on the web, it expands to `http://sitename//css/screen.css`

The `//` is really important because it shows the there's already a slash in `%HOME_PATH%` if it's needed.

The working directory for the export where index.html lives is in a directory that only the browser has a name for, and _all_ URLs in the export must be relative. In the directory where index.html is, `%HOME_PATH%` is the empty string, and the resulting URL for the markup above is `/css/` which is absolute, not relative, so it can't possibly work unless you want to hardwire the directory structure completely. That'll work on a CD-ROM, but the files will likely break if they are copied. With the all-relative approach I took, the files can be anywhere, but you have to make sure that the URLs all stay relative.

In nested directories like collections, `%HOME_PATH%` will map to `../` or `../../` or some other path depending on the nesting.

so try this:

```

@import url('%HOME_PATH%css/screen.css');
@import url('%HOME_PATH%css/base.css');
@import url('%HOME_PATH%css/print.css');
```

You should always test the output of the macros by themselves if things are getting confusing. _If_ I remember correctly, the only real difference between `%HOME_PATH%` and `%HOME%` is exactly that trailing slash...

**Comment by orangedrink** [comment] 2012-08-07 19:40
I don't think you read what I posted.

This goes in:
@import url('%HOME_PATH%/css/screen.css');
@import url('%HOME_PATH%/css/base.css');
@import url('%HOME_PATH%/css/print.css');

This comes out:
Unknown template call BAD@import url('/css/screen.css');
@import url('/css/base.css');
@import url('/css/print.css');

**Comment by orangedrink** [comment] 2012-08-07 19:41
When this goes in:
/\* %HOME_PATH% */

This comes out:
Unknown template call BAD/\*  */

You do remember the problem we are trying to solve here right? Let me know if you need a refresher.

**Comment by daviddurand** [comment] 2012-08-07 20:15
Yeah, all this came up in an email thread in May, with a discussion of few alternatives to `%HOME_PATH%` as well. just for reference, here's some of the past conversation:

Me->David:

Again, to be sure, you mean that a link like this doesn't work to
access a file called foo.txt in the home directory (where index.html
lives):

```
<a href="%URL_SITE_HOME%/../foo.txt">
```

And again this isn't working because the result of substituting the
`%URL_SITE_HOME%` into that link is not giving a URL that will work. I'm
specifying this just in case you were trying something else.

David->Me

Right. When I put this into a layout block:

```
<a href="%URL_SITE_HOME%/../foo.txt">
```

This is what I get out (on pages other than home):

```
<a href="../index.html/../foo.txt">
```

After testing this again it looks like it does work in chrome. If you think this will work well across browsers I'm open to trying it this way. `%HOME_PATH%` would be preferable though.

Me->David again:

At least in the URL box on my browser, a url like that will remove the
file component from a URL. _actually,  checked, and it has to work because that's what the HTML RFC says._

It may be trickier on the export because I have to use relative URLs
everywhere, since I don't know where the zip will be unpacked, so I
can't use "/" as a reference point anywhere in the markup.

> It seems to me like the behavior of this macro on a static export makes it
> pretty useless except in the case that we are linking to the home page.

From this I'm assuming that %URL_SITE_HOME% always produces a url path
that contains "index.html" on site export, and that is causing trouble
when you want the site root path. So it's working as designed, just
not doing what you want. I just need to need to be sure if I'm
addressing a bug or a design issue.

David->Me

Right. It is working as designed. Since it does seem to work when I use it properly it's not at all useless but I'm not sure it's the best solution in the long term. Again if you think it will work in all browsers then I can go along with that. Maybe not an issue if we will have `%HOME_PATH%` instead.

**Comment by orangedrink** [comment] 2012-08-07 20:39
So you'll fix it?

**Comment by orangedrink** [comment] 2012-08-08 15:20
When this goes in:
     /\* %HOME_PATH% */

This comes out:
     Unknown template call BAD/\* */

Just want to make sure you are aware of and working on this. Please verify that that is the case.

Thanks.

**Comment by daviddurand** [comment] 2012-08-08 16:04
I owe you an apology! Our last two posts crossed in the browser, and I had not understood that the bug was in the expansion of `%HOME_PATH%`. With all the extra context, I thought the error was coming from somewhere else, and the extra slashes actually stuck out to me more than you would expect (because that kind of thing has caused a lot of issues in the past). This is happening on the site export only, if I understand things finally, so I may well be able to get it fixed in the next hour.

### UPDATE

OK, I found two things -- one is that it turns out that not all macros were being substituted in CSS style sheets, only the `PARAM_` macros. I did not even know that, and my macro substitution tests did not take that into account (they were based on HTML blocks, which are easier to test) -- and that is why %HOME_PATH% was working differently in stylesheets, and I was not even seeing the bug. I've got that under control already. The other problem is that there's some caching code to make CSS delivery faster, and it is interfering with the site export, so that it does not always get the right version of the stylesheet -- I'm going to work on that now, and then we'll get the fixes live.

**Comment by orangedrink** [comment] 2012-08-08 17:31
OK. Thanks David

**Comment by daviddurand** [comment] 2012-08-08 20:57
OK, `%HOME_PATH%` is working now, and _all_ %-macros are now substituted in CSS sheets, just as they are elsewhere. It's not using the wrong stylesheet either any more.

**Closed as completed by daviddurand** 2012-08-08 20:57 UTC
Labels: question

**Comment by orangedrink** [comment] 2012-08-27 20:44
Well it doesn't seem possible to do conditional "@import" css for our IE only stylesheets using this method. Any thoughts on that?

**Comment by orangedrink** [comment] 2012-08-27 20:56
We're going to try another way to make this work. I do think that we will want this to eventually work as is laid out in the SOW.
