### ISSUE TITLE
Error message on Contact Us Page

### ISSUE THREAD

**Issue by ghost** [Tizra/Tizra-Customer-Tracker#98] opened 2012-08-22 02:10 UTC
http://elibrary.asppa.org/~contactUs

On the bottom left of the page some error messages are showing up that weren't there in the past. 
I can try to hide them with css, but I'm wondering why it is there. It looks like it is being generated by your system because it is outside of our #wrapper div for the page.

Thanks.
Ryan

**Comment by daviddurand** [comment] 2012-08-22 15:18
You may need to hide those messages. They are happening because you are not using the built-in contactUs block, which generates a form in which the "error message" is simply a highlighted string near the form... On the first access to the form, the error message  is actually a prompt on all required fields. The ERROR headings at the bottom of the page are template defaults, since the extra information has not been displayed by the built-in form.

The contactUs block is part of the default designs, and people have not generally changed this form. What I see now is that there is a bug in that the form block is actually missing from the menu. I'm fixing the menu problem now, so that you can use the form block if you want to -- but you could equally well just hide the "errors".

I'll close this once the form block is available in the layout editor again.

This form was revisited because of the new sampling feature. Sampling access failures present the contactUs form, allowing collection of user information.

**Comment by ghost** [comment] 2012-08-22 15:46
I don't understand why text is showing up on the page when your form block isn't in the layout. To me, that seems like a bug.

**Comment by daviddurand** [comment] 2012-08-23 17:55
Well, it's not a bug, it's just the way it works, I'm afraid. We signal certain information to template-specific forms we generate by this mechanism, and if that information is not picked up by the form, it's treated as an error. We have the form block so that you can customize the layout of the page around it, but we don't guarantee that a page like this, or like the e-commerce pages, can be customized without using the system-generated form, as they have a lot of hidden display and processing logic.

If you you want to use a custom form on a template like this, you can use CSS to hide the information, or you can use javascript to pick it up and format it for display (the client-side equivalent of what our form does). If you copy markup, like forms, that is generated by the system, you may run into issues if the system approach changes. We do give instructions (and take effort to support) some customized forms like search, but not all features are designed for that kind of easy substitution. If we generate markup, we may need to change some details in that markup over time, and with a form like this that includes error checking and resubmission features, you can't write a custom form that actually works the same way (like preserving other user input if there's a missing email address, for instance).

Practically, I think you may be in pretty good shape for this one, as your issue surfaced when we added a lot of new options for the contactUs form -- you can add fields in the email area of the site settings, you can put the form on other kinds of pages, and you can use variables to tailor the email generated to include information about the page the form appeared on, and the values passed for the form elements you have added, and so on. With these new features, you may no longer need a custom form. I didn't even check out why the non-standard form was used, but for layout (rather than functional) issues, it's always better to stick to CSS, as otherwise functional change may break a page when the customization was not even essential.

**Closed as completed by daviddurand** 2012-08-23 17:55 UTC
Labels: client-support, has-workaround

**Comment by ghost** [comment] 2012-08-23 18:00
I disagree with you assessment because I don't feel like things should just show up when we don't intend for them to show up, or use those features. But clearly this isn't going to get us anywhere. 

I'll look at the forms you provide and hide this bug with css. 
Hopefully you don't use the class t-error in a lot of places.

**Comment by daviddurand** [comment] 2012-08-23 18:49
The class t-error can show up on any page, actually, as it shows up for errors. If you decide not to follow my recommendation to use the system form, you should be careful use very specific CSS to suppress just these errors on this page, otherwise you may disable important user feedback on a lot of other forms in the system, and risk losing error information that could help us track down system problems, in the future.

Your best use of your time would be to make the form we generate look the way you want, and not to try to work around it.

We failed to document that the contactUs form is needed on the contactUs page, but it seemed obvious given that the sole use of that page is to interact with specific server functions. You would not have had mystery messages if you didn't use the contactUs feature, or were using it in the way it is intended to be used.

To try to clarify the situation with respect to customizing forms, we cannot make any guarantees about the ability to replace forms generated by Tizra with your own hand-written markup except in some specific places where we have allowed this to meet customer needs, and we are accepting the burden of backwards compatibility.

I've made a Wiki page about forms customization.

https://github.com/Tizra/Tizra-Customer-Tracker/wiki/Customizing-Tizra-forms

**Comment by ghost** [comment] 2012-08-23 19:24
I don't think your forms will have the flexibility we need, but I will look into it. 

as for the css, I went with "body > .t-error {display:none}". Since our templates are all wrapped in #wrapper, and your error shows up outside of it, I shouldn't have any issues with hiding the unwanted text. I can't specify the page because your system doesn't class the body for specific pages.

**Comment by daviddurand** [comment] 2012-08-23 19:56
I have added a class to body tags to indicate the current view.

t-contactus will be the value on this page. 

t-error is an important style, and if you do what you propose you won't get any error feedback in user registration forms, e-commerce, etc.

change will be live in 20 minutes or so.
