### ISSUE TITLE
Changes to Sort By field of list block not taking effect.

### ISSUE THREAD

**Issue by orangedrink** [Tizra/Tizra-Customer-Tracker#19] opened 2012-02-06 15:16 UTC
To reproduce:
1) Go to asppa.tizrapublisher.com/admin/main
2) Click content>static pages>the source
3) Under design layouts click static page content
4) Click edit in the list block labeled the buggy one
5) Change the sort by dropdown to chapter
6) Click update
7) Click edit on that list block again
8) Sort by has reverted to publication date

I've tried dragging the whole layout to the workbench and back but it doesn't help. This seems to me to be a separate issue. This is also happening with the list block in our main nav bar master block and I would assume in other places as well.

**Comment by daviddurand** [comment] 2012-02-06 15:49
I'll check into this right away.

**Comment by daviddurand** [comment] 2012-02-06 16:21
I found the source of this problem. Incidental result of some cleanup on Friday, Jan 27.  This will be repaired tomorrow, and designs that were not edited will be back to normal. In the case that a design had been saved after that date, you can either reset the list sorting value in the current desing, or reapply an older design and redo the changes.

Hopefully it won't block your progress too badly to have to mess with the list blocks again tomorrow. I'll do another review of the all changes in question looking for any similar issues and make any updates before we put the fix in place.

Thanks for this report, it was a nasty one, and hard to spot (it was caused by deleting of a private method with no calls to it -- but hidden accesses by the database mapping code (hibernate) -- which did not report the error).

**Comment by orangedrink** [comment] 2012-02-07 17:20
Any idea what time we can expect to see this fixed? I'd like to proof the new SDE conferences. Thanks!

**Comment by ghost** [comment] 2012-02-08 15:22
This problem is still impacting the "Collection Content Index" sorting.
To see the issue go to:
1. handouts.sde.com
2. Home > Presentation > Layout > Collection Home 
3. Edit "Collection Content Index"
4. Change "Sort by: Last published date" to "Sort by: Sequence"  
5. Change "Order of sorting: Descending" to "Order of sorting: Ascending" 
6. Click update
6. Click Edit "Collection Content Index" and the two changes revert to "Sort by: Last published date" and "Order of sorting: Descending"

The SDE spring Events and Documents need to be live tomorrow, but the order must be correct.

**Comment by daviddurand** [comment] 2012-02-08 16:27
Thanks for this.

I have been reviewing the change logs, scanning similar problems that may have come up during code cleanup -- but I either missed or had not gotten to this one. I'm writing this before I've finished checking it out because I'm pretty sure it's the same basic cause.

It should be fixed for SDE by tomorrow. I'll follow up again, once I have the final story.

Since it does require a restart to put a patch for this in place,  the fix won't be live until tomorrow (or at least later tonight). And of course you need it in place before you can apply the sort properly to the design.

If that's going to present a big problem, you can tell me exactly which blocks you need changed, and to how, and I can make sure that changes are in effect tonight after the fix is in place. If we do that I'll make any updates on staging and have you guys make the final check before pushing to live.

**Comment by daviddurand** [comment] 2012-02-08 16:29
yes, it was a similar bug, and we will make the fix live tonight.

**Comment by ghost** [comment] 2012-02-08 17:38
Since the fix can't happen till tonight, it doesn't help me proof the site today so don't worry about editing anything when you make the change live.
Thanks.

**Comment by daviddurand** [comment] 2012-02-08 21:46
The fix was made live this afternoon.

**Closed as completed by daviddurand** 2012-02-08 21:46 UTC
