### ISSUE TITLE
SMRP Site ecommerce not working

### ISSUE THREAD

**Issue by orangedrink** [Tizra/Tizra-Customer-Tracker#157] opened 2012-12-07 22:01 UTC
To reproduce fill out the first ecommerce step page and click verify information

http://screencast.com/t/I5roL854Z

**Comment by daviddurand** [comment] 2012-12-07 23:39
Thanks for this. I would have helped to have the site URL (I was able to look it up).

The problem is fixed now -- It only showed up for sites _not_ using the cart, which are now pretty rare, and was a regression of an old bug.

You need to test this with an offer published to the live site. Even if you start from the testing site, the system enforces a secure URL (by redirect) for all of credit cart operations. This pops the resolution process over to the live site -- for paypal at any rate. 

The fix is now live.

**Closed as completed by daviddurand** 2012-12-07 23:39 UTC
