### ISSUE TITLE
Publishing Error on ASPPA site

### ISSUE THREAD

**Issue by ghost** [Tizra/Tizra-Customer-Tracker#186] opened 2013-03-05 16:31 UTC
http://screencast.com/t/UVIe7rT08F

I have published all the 2012 files to live and I'm currently working on getting all the 2013 files uploaded to staging. The file I was trying to upload was Chapter 5 (Chapter 5, Section 415 Limits) and I got the error in the screen shot above.

I only have 4 files left to get to the staging site.

**Comment by ghost** [comment] 2013-03-05 16:36
Error did not show up for Chapter 6.

Trying Chapter 5 again

**Comment by ghost** [comment] 2013-03-05 16:37
Chapter 5 got the same error.

**Comment by ghost** [comment] 2013-03-05 16:49
Same Error on Chapter 8, Coverage Testing
Same Error on Chapter 9, Nondiscrimination Testing

**Comment by daviddurand** [comment] 2013-03-05 17:02
I think that it has to do with the page counts of the updates, and how they compare to the page counts of the existing files. Let me look a little more. Thanks for the extra info, as it will help a lot.

**Comment by daviddurand** [comment] 2013-03-05 17:08
Please try adding a blank page to chapter 5 or chapter 9 (as they are only one page shorter than the 2012 versions). If they publish after adding a page, you may be able to proof those two as well, and we can be more sure that it's the count and not the state of the database that is causing the problem.

more news shortly, I hope.

**Comment by daviddurand** [comment] 2013-03-05 17:09
Can you tell me from the progress bars how far along the publishing operation seemed to be?

**Comment by daviddurand** [comment] 2013-03-05 17:24
At this point I'm seeing different results on the live system and my test system for identical files. The problem on the live system does seem to occur when publishing shorter documents to staging, and not ones with the same number of pages, or more pages as are already published to live.

**Comment by daviddurand** [comment] 2013-03-05 18:26
I think I have a workaround, for now.

do a metadata-only publish to staging, and the publish to staging....

I just tested this with chapter 9 and had success.

**Comment by ghost** [comment] 2013-03-05 18:29
OK, that seemed to work.

**Comment by daviddurand** [comment] 2013-03-05 18:34
We still have to find and fix the cause, but as I can't yet replicate it on my test system (though I can on a test account on the live server), it may be harder to track down than I would like.

**Comment by ghost** [comment] 2013-03-05 18:35
Now that I have a way to move forward with proofing, I'm good.
Let me know when you are able to find the problem and get it fixed. 

I'll let everyone here know that this issue exists just in case they run into it, but using the staging site like this will be rare for us.

**Comment by daviddurand** [comment] 2013-03-05 18:56
It's been rare for all our customers, which is how the problem had escaped us until now.

**Comment by daviddurand** [comment] 2013-03-06 16:14
I have found a fix for this. I tested with a test site on the live server, as well as on the development box, and it's working, so the workaround should no longerbe needed. If you run into trouble in the future with this, please report it, even if this old workaround seems to fix the problem.

**Closed as completed by daviddurand** 2013-03-06 16:14 UTC
Labels: bug, has-workaround
