### ISSUE TITLE
ASPPA site has no controls when documents appear in full screen mode

### ISSUE THREAD

**Issue by orangedrink** [Tizra/Tizra-Customer-Tracker#103] opened 2012-08-28 17:36 UTC
To reproduce visit http://s64705085-preview.tizrapublisher.com/erisa-outline-book-chapter-1a/1 and click the full screen button

Let me know if you have any questions.

**Comment by orangedrink** [comment] 2012-08-28 17:39
#99

**Comment by daviddurand** [comment] 2012-08-28 18:16
This is a duplicate of #99, and also seems to be fixed at this point.

**Closed as completed by daviddurand** 2012-08-28 18:16 UTC
Labels: duplicate
