### ISSUE TITLE
Publish of new version to staging produces error when attempting to preserve current live

### ISSUE THREAD

**Issue by ghost** [Tizra/Tizra-Customer-Tracker#182] opened 2013-03-01 21:09 UTC
When I try to publish a file (Chapter 15, Tables, Checklists, and Quick Reference Guides) to Staging, I get the following error message: http://screencast.com/t/sXELUAjHs6kk

I had to remove the new file so that I could upload the old file because the ToC from both the new and old file were showing up on the live site. We had this happen once before on another chapter, but I don't notice it on any other at the moment.
Now I need the New file on staging for proofing, but I get the error.

**Comment by daviddurand** [comment] 2013-03-01 21:21
It was a caching issue, (I suspected so from the "staleStateException"). By the time I tried the operation from here, it was fixed, and it's now republished...

It's possible that a file published long ago might run into problems with interference between the live and staging versions of the ToCs, as there were some bug fixes to the publication process over the last year.

**Comment by ghost** [comment] 2013-03-01 21:25
The file wasn't suppose to be published live only to staging. I never clicked publish staging and live but now it is in both spots. Why did that happen!

**Comment by daviddurand** [comment] 2013-03-01 21:33
I did the wrong thing... which is why I try never to publish to live. Broke my own rule.

My guess is that documents in question won't support publishing to staging only with a new PDF until they've been unpublished first (that clears out any old problems).

You may just want to put the new PDFs in a new document for proofing...

**Comment by daviddurand** [comment] 2013-03-01 21:49
In testing, I have found that publishing a new PDF to staging after deleting an old one (which is published to live), will dependably reproduce the error you encountered.

We are working it now...

**Comment by daviddurand** [comment] 2013-03-02 03:50
Found a database issue that was causing problems on any attempt to publish to staging when the document was already published to live. Some documents published more than a year ago might not have had this problem (because staging and live were managed differently at that time).

In any case, the problem is fixed, and it should be fixed for all documents, regardless of their history.

Thanks for the bug report.

**Closed as completed by daviddurand** 2013-03-02 03:50 UTC
Labels: bug, client-support
