### ISSUE TITLE
Creating documents on BS site is very slow

### ISSUE THREAD

**Issue by orangedrink** [Tizra/Tizra-Customer-Tracker#154] opened 2012-12-04 15:14 UTC
I'm trying to create a bunch of documents on bs53210.tizrapublisher.com 

When I create a new document the document properties page doesn't load completely. Even if I'm able to fill in the needed info I have to wait up to a couple of minutes before I can save the document.

To reproduce create a new document and try to save it.

I'm getting pretty far behind with this job. Please hurry!

**Comment by daviddurand** [comment] 2012-12-04 18:55
Sorry for not having commented earlier. I've been working on this all day. It's a serious regression in performance optimization for very large sites, which I've been working on tracking down. Admin for really big sites like TRB is unusable right now, with delays of minutes to display a single page from the list of all publications.

**Comment by daviddurand** [comment] 2012-12-04 22:35
I found the problem, and will be doing a server restart sometime after 6 Eastern to reset. Looks like you have some publishing going on, so that may need to be restarted once things are back to normal. Will close this issue once the restart is complete.

**Comment by orangedrink** [comment] 2012-12-04 22:50
OK thank you.

**Comment by daviddurand** [comment] 2012-12-04 23:07
The delays are now gone.

**Closed as completed by daviddurand** 2012-12-04 23:07 UTC
Labels: bug
