### ISSUE TITLE
Error when adding license to account set 

### ISSUE THREAD

**Issue by orangedrink** [Tizra/Tizra-Customer-Tracker#20] opened 2012-02-07 14:24 UTC
To replicate:
1) Go to handouts.sde.com
2) Click users
3) Click account sets
3) Click all users
4) Under set licenses click create new
5) Click create
6) Receive the error message "on operation view"

**Comment by daviddurand** [comment] 2012-02-07 15:25
This is a problem in the new email code. I've found a fix, and we'll look at the feasibility of getting an immediate patch in place.

Right now there is no workaround.

Had this error showed up on the Testing site for you? I wasn't seeing it, but I remember your mentioning that user sets did not send mail.
While that was by design, I didn't remember any other error.

In any case, I hope we'll be able to get the patch in place in a couple of hours at the most.

**Comment by orangedrink** [comment] 2012-02-07 15:43
No. I don't remember having a problem with adding licenses on the test site.

**Comment by daviddurand** [comment] 2012-02-07 20:50
Thanks. The bug is fixed now. Sorry for the delay, the server has been so busy it was hard to find a good time to apply the patch.

**Closed as completed by daviddurand** 2012-02-07 20:50 UTC
