### ISSUE TITLE
SDE users cannot see entire collection listings

### ISSUE THREAD

**Issue by orangedrink** [Tizra/Tizra-Customer-Tracker#77] opened 2012-07-03 21:21 UTC
To reproduce:

1) Go to http://handouts.sde.com/C900/ but do not log in.
2) Notice the many documents listed under the sub heading "National Conference on Differentiated Instruction" about 1/4 of the way down the page.
3) Log in to a non administrative account. You can use mine if you like  U: dfranks@omnipress.com P: 123
4) Notice the documents under the sub heading "National Conference on Differentiated Instruction" have disappeared.

**Comment by orangedrink** [comment] 2012-07-03 21:23
I set things up in a similar way here http://handouts.sde.com/C850/ but I'm not seeing these problems.

**Comment by daviddurand** [comment] 2012-07-03 22:20
About 45 minutes ago I republished the collection to staging and live, and the C900 page is now working for me (logged in or not). Not sure if there was a problem other than publication status (it did not appear as if the access restrictions were incorrect, I just wanted to make sure).

It's conceivable that there was a visibility-checking bug where unpublished content was erroneously visible (I found a bug like this a while ago for excepts). Why login status would affect that, I don't know, but the visibility checks are complicated -- I'll look into it. In any case, ensuring that it was published seems to have done the trick, so I'm pretty sure that it hadn't been properly published for some reason.

You called at the minute that I was rushing Elli and Despina to the train to catch a plane to Greece, so I just whacked things as fast as I could using the iPad. I could not get you on the phone once I was back in the house because the switchboard and omnipress had closed.

I'll leave this open while I check for any display bugs that may have made the (probably) unpublished collection display in error. but unless I hear otherwise, I am assuming the crisis is over.

**Comment by daviddurand** [comment] 2012-07-04 00:54
I looked around for bugs of the sort that I suspected, and could not find any. The interaction of the layout and content editors can be confusing, however, when you you are overriding the layout for a special page (as the collection home page seemed to be). You have to republish the site design to get the effect of such an overriding change to take effect, and perhaps that could have led to some problems with the admin tag filtering on the collection contents blocks. I'm going to close this on the 5th, unless I get a report of some continuing problem that I am missing.

**Comment by orangedrink** [comment] 2012-07-04 03:59
Thanks for getting to this so quickly David. I'll let you know if we see any More problems.

**Comment by orangedrink** [comment] 2012-07-07 14:20
Users are complaining about this same issue again. I can't reproduce the problem so maybe it was a short lived one but it looks like we will need to find the underlying cause to keep it from continuing.

**Comment by daviddurand** [comment] 2012-07-07 15:00
From: Wufoono-reply@wufoo.com
To: digital@omnipress.com, msheldon@sde.com, kkurinskas@SDE.com, pvenning@sde.com
Cc: 
Date: Fri, 6 Jul 2012 23:14:27 -0700
Subject: SDE Handout Center Technical Support [#388]

Name \*  Claudia Curbelo
Email \* curbelo.Claudia.A@muscogee.k12.ga.us
Phone Number \*  (706) 987-3969
What web browser are you using? 
IMPORTANT: Make sure to include the version. \*  
Chrome - latest version
What version of Acrobat Reader do you have? 
Adobe Acrobat X (version 10.0)
Describe in further detail what site error you are experiencing so we can help fix it. \*  
Do not see any handouts for the sessions, except for administrator summit and powerup. Do not see any sessions that start with D.
Job Number  
50082
Product Type  
Knowledge Center
Website (if applicable) http://handouts.sde.com

From: Wufoono-reply@wufoo.com
To: digital@omnipress.com, msheldon@sde.com, kkurinskas@SDE.com, pvenning@sde.com
Cc: 
Date: Fri, 6 Jul 2012 22:16:55 -0700
Subject: SDE Handout Center Technical Support [#386]

Name \*  Bonnie Barrett
Email \* teachr4ever2@yahoo.com
Phone Number \*  (602) 670-1188
What web browser are you using? 
IMPORTANT: Make sure to include the version. \*  
FireFox
What version of Acrobat Reader do you have? 
Adobe Acrobat 7.0
Describe in further detail what site error you are experiencing so we can help fix it. \*  
I am not getting the whole list for all of the classes. I am only getting the administrator and power up lists. I need the rest of them to download what I need. Please let me know what I need to do. Thanks.
Job Number  
50082
Product Type  
Knowledge Center
Website (if applicable) http://handouts.sde.com

**Comment by daviddurand** [comment] 2012-07-07 15:10
OK, when I go to the directory page I see all the sessions, including the "D" sessions.

Using his account and a fresh browser. So the problem, if it exists, is an intermittent one.

I see that the display of individual sessions in the right margin is suppressed (by the style sheet).

Perhaps adding that list back might help by making the design more clear. I don't see any data problems in the account record.

I'm wondering if perhaps there's a problem if someone tries to access an account during a bulk account upload? Both the database and the full-text search are involved in that process, and there could be some concurrency issues with the updates. We can if an upload was going on, and I can check the logs for any messages that might indicate other potential issues as well.

For Claudia.curbelo the registration info looks like this:
C900/DH12; C900/DE12; C900/DD18; C900/DA29; imported; C900/DC18; C900; C900/DA18; C900/DF14; C900/DD36; C900/DE29; C900/DB06; C900/DF31; C900/DB27; C900/DG02

She'll have to reset her password (will look like a new registration), as I had to change it in order to test whether things were working.

**Comment by daviddurand** [comment] 2012-07-07 15:46
Updated previous comment to reflect that we have the time of the bug reports, at least, so that the problem is pretty close. Let's check if there was an upload going on, just in case.

I notice that both reports are around 15 minutes after the hour. If we were to notice a regular pattern around this there are some periodic tasks that take place on that schedule -- not anything that I can imagine affecting this, but we can keep our eyes open in case it's not a coincidence (which is what I think right now). You might be able to tell that I'm reaching, at this point.

I just can't find anything. My guess is that it will have something to do with the account loads. Perhaps a locking issue during account loads (which would be quite a bad thing, but I don't expect it), or, more likely, problems with individual account records -- missed loading errors, or something like that.

**Comment by daviddurand** [comment] 2012-07-07 16:31
I checked more in the logs. Garbage collection is out of consideration, as it was completed before curbelo's problem.

Both accounts were just claimed at the time they had the problem. Perhaps there's something happening in the claim process -- but I could not replicate it. It might be safe advice to tell teachers to log out, and log in again, but if they do that, it's really important that they find out if it helps -- and let us know! Also, we need to have a better sense of how often this is actually happening, and how...

**Comment by daviddurand** [comment] 2012-07-08 18:00
I was talking through the debugging process with Steve yesterday, and at the moment I've really only got one theory. I was basically racking my brains to try to figure out how a problem like this could exist, and be so hard to replicate, without dismissing the bug report either (it seems hard to get wrong). At the moment the only thing that I can think is that it must be a transient thing, most likely a dropped HTTP connection. A few months ago we switched the page delivery to browsers to use `Transfer-encoding: chunked` -- that means incremental page delivery as opposed to the whole-page model of normal HTTP. We did that so that long list pages like this one would feel faster to users because they could see display progress even while the server was still building the page).

If the session dropped in the middle due, say, to a network error of some sort, the browser could display a partial page without the error that would occur if a non-chunked page connection was interrupted. You could tell visually because some of the page (probably the footer, at least) would not display. But a teacher might not notice that, and the one time I saw the error, I was using an iPad, and was too focused on trying to make a fix before I had to go to the train station to notice if there were other problems on the page like that.

Right now, it's the most likely idea I can come up with. Certainly if you see the error again, you should save the downloaded HTML source, and perhaps take some screen shots too, so that we can check for anything in the HTML, or any incompleteness.  I'll do the same.

**Comment by orangedrink** [comment] 2012-07-11 15:23
Will do. I have also only been able to actually witness this problem once but I'll keep an eye out.

**Comment by daviddurand** [comment] 2012-07-13 15:00
I'm going to close this until we get enough evidence to investigate further.

**Comment by orangedrink** [comment] 2012-07-16 14:43
I haven't heard of any more users having this problem.. _shrug_

**Comment by orangedrink** [comment] 2012-07-18 15:05
SDE is complaining about this one again.

**Comment by daviddurand** [comment] 2012-07-18 18:52
Well, let's see if we can get some more details of who is seeing it, and when and how.

I'll look to see if I can find anything, but I'm going to need some information on where to look...

**Comment by orangedrink** [comment] 2012-07-18 19:38
I'm a bit at a loss here too.

It seems to happen to only a few users and for a certain duration of time. I'll see what other details I can find out.

**Comment by orangedrink** [comment] 2012-07-18 20:15
I'm going to try to write a script that downloads the index every hour and see if we can capture this happening.

**Comment by daviddurand** [comment] 2012-07-18 21:59
I've been looking at the logs, and I can see occasional short page
deliveries, but they always seem to be explainable as dropped browser
connections.

There are no errors showing up in the log that seem related to the errors.

I'm wondering if there is some kind of interruption happening in the
browser. Is there any way you can think of that any of the scripts
could stop the rendering or download? is it still only happening with
that one page? It does seem to me that reloading the page is as likely
to fix things as going to the alternate page (as it does the same
things).

**Comment by orangedrink** [comment] 2012-07-18 22:47
No I don't see what the scripts would be doing to stop rendering. Also it
seems like if this was on the client side the reports would be less
consistent as far as what shows and what doesn't. Hopefully tomorrow I'll
have captured a "short page" and I can tell you if the footer appears or
not.

**Comment by daviddurand** [comment] 2012-08-01 17:12
I believe that I have found what might have been the problem. A recent revamping of error reporting has meant that some search index errors that were being erroneously suppressed are now being reported properly. This showed up as a bug in the search index isolation that I implemented a while ago, which prevented the old phenomenon of search index (and list block) errors when the search index changed behind the scenes during a page display.

Yesterday, the new reporting led to template errors on TRB, during your mass publishing operation. I noticed the errors late in the day, as I didn't even know it was happening, but previously a search that hit an error like this would have been silently truncated. I found the bug, which was subtle, and only shows up pretty occasionally even under production load conditions. So it will be fixed tonight.

My memory indicates that you were in the process of doing some large publishing operations during the times that the SDE errors were occurring. I never even thought of it, since there were no log messages, and I knew that I'd implemented some pretty careful controls on the search indexing. Long list publishing is most likely to cause the problem, because it depends on lots of transactions happening during the delivery of a page, so there has to be relatively high site load, as well as frequent publishing. Since papers are short, they publish pretty quickly, and SDE load was extremely high, so it was a perfect scenario for having the problem show up.

If your memory agrees with mine and publishing was going on during the times they were reporting errors, then I think we have the solution to this problem for once and for all.

If you don't tell me that I'm wrong about this, I will close this issue once the new fix goes live.

**Comment by orangedrink** [comment] 2012-08-01 17:40
No there wasn't any publishing going on at those times. The high traffic part fits though.

**Comment by daviddurand** [comment] 2012-08-03 22:39
The issue that I was thinking of could not have occurred without write traffic to metadata or full text content. There are a few situations in which the system could reindex content, and perhaps this was happening. It was also possible for stale results to linger in the search cache, which now can't occur.  I am closing this issue, since the search internals have been revamped, and I believe the only sensible underlying explanation to be something in the search infrastructure.

If it recurs, update it and we will reopen.

**Closed as completed by daviddurand** 2012-08-03 22:39 UTC
Labels: client-support, not reproducible
