### ISSUE TITLE
AGA allows purchase of the same content twice

### ISSUE THREAD

**Issue by SeanLawler** [Tizra/Tizra-Customer-Tracker#391] opened 2015-07-30 15:00 UTC
Buttons are grabbed from the offer page via AJAX. For example, this page: http://aga.conferencespot.org/sg3q-2014

It looks like that offer page now shows the buttons whether you already have access to the content or not.

Here's a video showing it http://screencast.com/t/in5nW2C5aJ2d

**Comment by daviddurand** [comment] 2015-07-30 17:09
The contextual offer block displays links to offer pages (and/or direct buy buttons). If you use that, and customize the display, rather than trying to fetch from another page, the link display will be properly controlled. the block will only display offers for content that the user cannot access already, and it uses the display context (what the user is viewing, or was denied access to) to determine how those offers would be applied: for instance, collection offers are displayed only when they contain the content in question.

The offer's page itself always displays the purchase link (since it's expected that people arrive there via the offer block, or because they were sent by a publisher.

If the offer page ever did not display the link, it was almost certainly a bug of some kind, and if you have an example that would be interesting to look at.

This is the way it was designed, and the lack of complete protection from double transactions (for the determined), is a well-known limitation.

**Comment by orangedrink** [comment] 2015-07-31 13:34
That limitation was not well known to us. If that was the way it was designed then I feel that it's a poor design but I know that there's no way we will ever convince you to rethink it.

Go ahead and close this. We'll work on an alternative way to accomplish what we need to for this customer.

**Comment by daviddurand** [comment] 2015-07-31 19:10
Stay cool... there are two solutions below

Multiple purchases are allowed because are not always an error, though for many sites they could be. That's why the system already offers the ability to present a list of offer links filtered by existing access rights.

The limitation I was referring to is that users who save old offer links, or sites that display them without using the contextual offer block, might enable a user to buy the same item more than once. (That's how you could make the same offer more than once, when it makes sense).  I actually do think that we will consider an enhancement to create a fulfillment error when someone attempts to buy a clearly erroneous duplicate license. (With Tizra's flexible licenses, this determination is not easy, as a customer might want to buy multiple licenses for the same content in order to increase concurrent accesses, for instance. There are actually a lot of cases like that, and the expense or difficulty of checking some of them may be prohibitive.)

However, a new, complicated feature will take some time, and would not solve your problem -- which is caused by using an AJAX access to the offer page, which is supposed to work as it does now, rather than the using the built-in function that already does what you want. All it would ensure is that your site would display a link that would give an error message when it was used.

### Solution 1:

Use the existing contextual offer block, as it handles a lot of complex checks; it also finds things like VirtualCollection offers that involve complicated logic that would be hard to replicate. If there's some limitation on the offer block that is blocking this approach, let us know, and maybe there's something we can do.

### Solution 2:

If the search you need is simple, and the offer block is presenting too many purchase possibilities (for instance), it is possible for you to get complete information on what a user has already purchased via the api, and to search for offers based on metadata, so you could create a reliable AJAX script that would combine this information to give you what you want.

These are all described on this page:

https://github.com/Tizra/Tizra-Customer-Tracker/wiki/JSon-Query-Interface

licenses method:
`/api/query/licenses`

When searching for offers, you should use the meta-type `Offer` with one of the search interfaces: `/api/query/match` or `/api/search`.

**Comment by orangedrink** [comment] 2015-07-31 19:32
Ok. Thanks for your help David. I'll take a crack at solution 2 and will let you know how things go.

**Closed as completed** 2022-10-11 20:07 UTC
Labels: enhancement, client-support, has-workaround
