### ISSUE TITLE
Zip files not working

### ISSUE THREAD

**Issue by aabercrombie** [Tizra/Tizra-Customer-Tracker#302] opened 2013-11-18 15:31 UTC
On ai.tizrapublisher.com, zip files are not downloading properly. Any link to a zip file takes you back to the homepage instead. Ex: on http://knowledgecenter.appraisalinstitute.org/res-comm-solar, the Pre and Post class links are zip files that should download on click. Takes you back to homepage instead. Issue noticed last Friday.

**Comment by daviddurand** [comment] 2013-11-18 19:32
We are very sorry!

As a result of backing out problem from this morning, Some URLs generated by Tizra do not have trailing slashes -- this will be fixed tonight, as we have found the cause of the problem, and can bring the system fully back up to date, but it can't be changed sooner without causing other problems.

Your site is using javascript to rewrite URLs in the Tizra markup, and that script is creating a bad URL. There are certainly other ways to solve this problem by using built-in Tizra features, but the easiest thing would be for you to change your script to include an extra `/` character before `~~Attachments` in the last couple of lines of kc.js.

This will not need to be backed out in the future, as the extra slash will cause at most an additional redirect, something that will not be noticed on a long operation like a download.

We are sorry for the problems today.

Since the script is on Amazon, it has to be changed at your end.

**Closed as completed by daviddurand** 2013-11-18 19:32 UTC
Labels: bug, has-workaround

**Comment by daviddurand** [comment] 2013-11-19 03:03
This is now fixed for good. No need to change the script if you haven't already.
