### ISSUE TITLE
Tag picker screens blank in USER section for 2 sites

### ISSUE THREAD

**Issue by cbwinchild** [Tizra/Tizra-Customer-Tracker#405] opened 2016-03-08 16:51 UTC
On Lab-Aids site, for example, if you click into the User Tag field on any Individual User account or into the the Matching Any/All fields for Account Sets, no User Tags display for selection (to add or delete). On most sites, it's working fine (cbw.tizrapublisher.com, for example). Clearing cache did not resolve. 

Work-arounds = enter New Tag and click Add; close picker screen and use Delete keyboard key.

**Comment by cbwinchild** [comment] 2016-03-10 16:06
Update 3/10/16: ASHP is seeing same issue, but within the CONTENT section as well. Tag Picker screens are blank.

**Comment by adane** [comment] 2016-03-10 16:29
Thanks, Catherine.  David is looking into this.  Can you let them know?

**Comment by daviddurand** [comment] 2016-03-10 16:56
This appears to be a problem caused by the presence of single quotes in the Display name of the property "Email Address for Institution's Contact". I have removed this, and things are working properly again.

This should not happen, but the workaround is easy (avoid the single quotes). We will close this ticket once the problem is fixed.

**Comment by daviddurand** [comment] 2016-03-11 00:45
These issues have been fixed for all sites and the fix deployed.

While Tizra does not impose limitations on content, There is a small list of characters whose use may expose lingering problems, especially in keyword values. These characters are:

`; " ' & < >`

**Closed as completed by daviddurand** 2016-03-11 00:45 UTC
Labels: bug, has-workaround
