### ISSUE TITLE
Text not displaying on index page

### ISSUE THREAD

**Issue by aabercrombie** [Tizra/Tizra-Customer-Tracker#320] opened 2014-02-26 18:06 UTC
Descriptions are no longer appearing in the indices for trb-hcm.tizrapublisher.com. (See picture below). We haven't updated this site since Nov of 2012, so I can't think of anything we'd have done to cause this change. Documents are still loaded properly, descriptions are there in the abstract field.

![hcm_error](https://f.cloud.github.com/assets/3876308/2273459/b66dde86-9f10-11e3-819f-1047a50b0c44.png)

**Comment by ghost** [comment] 2014-02-28 14:14
This is also happening on ASPPAs site. http://elibrary.asppa.org/erisa-outline-book/
Each chapter should have a description under them. 
We haven't made any changes to either of these site.

**Comment by daviddurand** [comment] 2014-02-28 15:50
I just tracked this down. A new feature allows the data types of built-in properties to be adjusted (creating site-specific overrides for the). The Show? flag on those properties was incorrectly changing the system definition rather than creating an override.

The ability to do this is now removed, and the properties are being returned to their normal visibility settings -- the abstracts are already back.

**Comment by ghost** [comment] 2014-02-28 21:57
And the problem is back...

I check both of these sites after you closed this, and it looked fine. Now they once again do not have text coming through.

http://elibrary.asppa.org/erisa-outline-book/
http://hcm.trb.org/v1/

**Comment by daviddurand** [comment] 2014-02-28 22:18
I removed the bug that let this change happen, and I'm hoping that the return was due to some stale cache entry rasing its head. I've manually flushed things, and I'll check after a restart tonight. I'll re-open this until we can confirm that there's not another way for this problem to happen.

**Comment by daviddurand** [comment] 2014-02-28 23:11
It really is back. I found out why, but the fix will be later tonight. In the meantime I've used a property override to set these sites so the problem won't hit them in the meantime.

I did that by "editing" the property definition and just changing the user visibility.

**Comment by daviddurand** [comment] 2014-02-28 23:58
This should _really_ be fixed now. Will leave ticket open until tomorrow just in case.

**Closed as completed** 2014-03-05 18:25 UTC
Labels: bug, has-workaround, urgent
